### PR TITLE
Fix duplicated instances when dragging sortable with sortable childs

### PR DESCRIPTION
**Pull request by ghost**
Code pen demonstrating the bug is fixed: https://codepen.io/James-St-Pierre/pen/ZEZZqew

Closes 
https://github.com/stimulus-components/stimulus-sortable/issues/16 (Lots of good information here)
https://github.com/stimulus-components/stimulus-sortable/issues/8
https://github.com/stimulus-components/stimulus-components/issues/60

**Explanation:**

When you have a draggable list that have children with draggable list, it means both the parent and child have `data-controller="sortable"`

What happens when you drag around the **parent** list item, SortableJS moves the item using `appendChild` or `insertBefore` or other means that do not disconnect any connected event handlers. However, this seems to trigger Stimulus connect/disconnect callback on the child as they are dragged on so this library destroy and re-instantiate a new sortable instance everytime while this is unnecessary. Calling .destroy() on the child sortable while dragging the parent seems to stop the dragging process and that is what users are reporting

**Drawbacks**

If really an element was actually removed while dragging an item, we wouldn't destroy the SortableJS instance. 

It reallty 

We could lower the risk by checking if the disconnected item is actually a child of the dragged item (`Sortable.dragged`) however that wouldn't actually mean with 100% certainty the element is being removed.

Another thing that could be done is maintaining a map of all elements and have a `setInterval(...)` or something that checks every x seconds if elements are still present in the DOM and after a few consecutive ticks destroy the instance. Not sure what happens if this happen while dragging a non-related item.

A third solution could be listening to turbo:load to get rid of all previous instances.

### CODE REVIEW

**Comment by ghost** [comment]
@guillaumebriday Any chance you can have a quick look? :)

**Review by MiltonRen — COMMENTED** [review]
I found that disconnecting throws errors when I'm on mobile. This would fix the errors in my environment:

```
    if (!Sortable.active && typeof(this.sortable) != "undefined") {
      this.sortable.destroy()
    }
    this.sortable = undefined
```

**Comment by wnm** [comment]
any updates on this? 😇

**Comment by wnm** [comment]
> If really an element was actually removed while dragging an item, we wouldn't destroy the SortableJS instance.

@james-em can you say a bit more on when or why that would even happen?

**Comment by jamesst20** [comment]
> > If really an element was actually removed while dragging an item, we wouldn't destroy the SortableJS instance.
> 
> @james-em can you say a bit more on when or why that would even happen?

It's unlikely but not impossible. I.e while you're dragging there is like a promise that resolves and deletes an element or maybe some kind of websocket events that happens while you're dragging

**Comment by guillaumebriday** [comment]
Could you reopen this PR into the main repo https://github.com/stimulus-components/stimulus-components? Thanks!!

**Pull request closed without merging**
