### PR TITLE
Return response after update

### PR DESCRIPTION
**Pull request by iainbeeston**
Right now it's impossible to do anything with the response from onUpdate() when subclassing. I'd like to be able to examine the response object and take further actions depending on the result.

To make this possible, I've returned the response, which I think should make it possible to use it if needed.

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Nice! Can you add this change in the Changelog?

**Comment by iainbeeston** [comment]
@guillaumebriday Done! ✅

**Comment by iainbeeston** [comment]
Sorry to bump this @guillaumebriday but can this be merged and released? 🙏

**Comment by guillaumebriday** [comment]
Thanks @iainbeeston 

Available here https://github.com/stimulus-components/stimulus-sortable/releases/tag/v4.1.1

Let met know if everything is working properly for you

**Pull request merged**
